(* ::Package:: *)

(* ::Input:: *)
(*loc="/home/s1373240/research/results/batchJobs/concRuns/lambdaScan2/";*)
(*means2 = Import[loc<>"densMeans.dat", "Data"];*)
(*errs2 = Import[loc<>"densErrs.dat", "Data"];*)
(*flow2 = Import[loc<>"rateMeans.dat", "Data"];*)
(*flowErr2 = Import[loc<>"rateErrs.dat", "Data"];*)
(*histMeans2 = Import[loc<>"histMeans.dat", "Data"];*)
(*histErrs2 = Import[loc<>"histErrs.dat", "Data"];*)
(*blockDev2 = Import[loc<>"blockDev.dat", "Data"];*)
(*flowMeans2 = Import[loc<>"flowMeans.dat", "Data"];*)
(*flowVars2 = Import[loc<>"flowVars.dat", "Data"];*)
(*flowSkew2 = Import[loc<>"flowSkew.dat", "Data"];*)
(*flowKurt2 = Import[loc<>"flowKurt.dat", "Data"];*)
