import foldyFloatList
ffl = foldyFloatList.foldyFloatList
a = ffl()
a.addValue(1.0)
print(a.toString())
a.addValue(2.0)
print(a.toString())
a.addValue(3.0)
print(a.toString())
a.addValue(4.0)
print(a.toString())
a.addValue(5.0)
print(a.toString())
a.addValue(6.0)
print(a.toString())
a.addValue(-1.0)
print(a.toString())
a.addValue(7.0)
print(a.toString())
a.addValue(-8.0)
print(a.toString())
a.addValue(1.0)
print(a.toString())
a.addValue(3.0)
print(a.toString())
a.addValue(-10.0)
print(a.toString())
a.addValue(3.0)
print(a.toString())
a.addValue(-18.0)
print(a.toString())
print(a.extractSum())
